BotsAppOfficial/BotsApp

modules/block.js
modules/unblock.js

Added a block.js file under modules directory.

Functionality - Block/Unblock Members

---

modules/invite.js

Signed-off-by: Mohit Singh Rana <mohitsinghrana_co20b5_18@dtu.ac.in>

Functionality: Share group invite link

---

BotsApp.js
modules/mute.js
modules/unmute.js

-  Added 2 files in modules folder (mute.js & unmute.js). 
-  Made a small formatting change for the display of args[] in the console (BotsApp.js)
-  '.mute' command will change the chat permission to 'admin only' and '.unmute' will change it to 'all 
group members'.
- .mute command along with a number argument will change the chat permission to 'admin only' only for the specified duration (in hours). After that, it will automatically revert back to 'all group members'.

Functionality: Added .mute & .unmute command.

---

Database/db.js
lib/db.js
modules/block.js
modules/id.js
modules/unblock.js

Functionality: Database file

---

.gitignore
BotsApp.js
core/helper.js
modules/add.js
modules/block.js
modules/demote.js
modules/invite.js
modules/mute.js
modules/promote.js
modules/remove.js
modules/unblock.js
modules/unmute.js
sidekick/input-sanitization.js
sidekick/sidekick.js
tmp/placeholder

Improvement: BotsApp class, Media handling

---

BotsApp.js
core/helper.js
lib/db.js
modules/help.js
modules/id.js
package.json

Functionality: Help Interface

---

.gitignore
core/helper.js
modules/admins.js
sidekick/sidekick.js

Signed-off-by: Johann <johannjose@msn.com>
- Added a key in BotsApp class by the name "messageReplyId" to store the stanzaId of the extended message
- Modified admins.js to incorporate tagging admins while replying to a message.

Functionality: Modified .admins command

---

lib/db.js
modules/admins.js
modules/mute.js
modules/unmute.js

- Added string messages for .mute, .unmute and .admins commands in the ../lib/db.js file.

String Database: Added preset messages for mute, unmute and admins.

---

lib/db.js
modules/add.js
modules/invite.js
modules/remove.js
modules/tagall.js

Signed-off-by: Mohit Singh Rana <mohitsinghrana_co20b5_18@dtu.ac.in>

Functionality: Tag all Members

---

config.js
lib/db.js
modules/demote.js
modules/neko.js
modules/promote.js
package.json
sidekick/input-sanitization.js

I have updated the string database and added the nekobin feature with conditions mentioned in the last meet.

Functionality: Nekobin and string database updated

---

lib/db.js
modules/getdp.js
package.json

Signed-off-by: Johann <johannjose@msn.com>

Functionality: Added .getdp command.

---

lib/db.js
modules/sticker.js
package.json
sidekick/input-sanitization.js

Added sticker.js file under modules directory. This can be used to convert any image or GIF message to a sticker

Functionality: Convert image/GIF to sticker

---

core/helper.js
lib/db.js
modules/disappear.js

Signed-off-by: Mohit Singh Rana <mohitsinghrana_co20b5_18@dtu.ac.in>

Disappearing msgs

---

core/helper.js
modules/stoi.js
sidekick/sidekick.js

Added stoi.js file in modules directory.

Functionality: sticker to image

---

modules/carbon.js
modules/neko.js
package.json

Functionality: Text to Carbon image

---

config.js
modules/weather.js

Functionality: Get weather data of enquired location

---

lib/db.js

Signed-off-by: Keshav Pahwa <keshavpahwa01@gmail.com>

Fix: Corrected a typo in db.js

---

package.json

Fixes the error where the bot wasn't working in new groups.
Reference: adiwajshing/Baileys#804

Fix: No response in new groups

---

BotsApp.js
database/blacklist.js
lib/db.js
modules/abl.js
modules/rbl.js
sidekick/input-sanitization.js

Add to blacklist using .abl 
Remove from blacklist using .rbl

Functionality: Blacklist

---

BotsApp.js
lib/db.js

Use "public" / "PUBLIC" or any other casing for public access work type. Anything other than this is counted as private.
Signed-off-by: Prashant-singla

Improvement: Private/Public access mode restriction

---

lib/db.js
modules/meaning.js
package.json

Signed-off-by: Mohit Singh Rana <mohitsinghrana_co20b5_18@dtu.ac.in>

Added Functionality: Search in Dictionary

---

modules/lyrics.js
package.json

[Improvement] - Fallback lyrics library
